### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by malonehedges** [flintjs/flint#165]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.1
**Thrown From**: [flint](https://github.com/flintjs/flint-atom) package, v3.10.1

### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At /Applications/Atom1.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1008

Error: Can't save buffer with no file path
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom1.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1008:15)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom1.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom1.app/Contents/Resources/app.asar/src/text-editor.js:557:26)
    at clear (/Users/malonehedges/.atom/packages/flint/lib/number.js:170:33)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-coffeelint",
      "linter-jshint"
    ],
    "projectHome": "/Users/malonehedges/code/",
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ]
  },
  "flint": {}
}
```

### Installed Packages

```coffee
# User
atom-dark-fusion-syntax, v1.1.0
atom-jade, v0.3.0
atom-pair, v2.0.10
autoclose-html, v0.19.0
autocomplete-emojis, v2.2.2
autocomplete-sass, v0.1.0
color-picker, v2.0.13
flint, v3.10.1
fold-comments, v0.5.0
fold-functions, v0.4.3
highlight-selected, v0.11.1
language-cjsx, v0.3.0
language-coffee-script-angular, v2.2.0
language-haml, v0.23.6
language-lua, v0.9.4
linter, v1.11.2
minimap, v4.16.1
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
new-file-plus, v0.2.1
nucleus-dark-ui, v0.6.12
pigments, v0.19.0
sync-settings, v0.6.0
xkcd-comics, v0.3.0

# Dev
No dev packages
```

**Comment by malonehedges** [comment]
It is spamming this error in Atom when I have a new window with a blank file (⌘⇧N).

**Comment by natew** [comment]
Moved to https://github.com/flintjs/flint-atom2/issues/21
