### ISSUE TITLE
Atom plugin: Uncaught TypeError: Cannot read property 'split' of undefined 

### ISSUE THREAD

**Issue by mglukhovsky** [flintjs/flint#203]
I'm running v6.7.0 of the `flint` package for Atom.

On pretty much every syntax error, the following plugin error pops up:

```
Uncaught TypeError: Cannot read property 'split' of undefined
/Users/michael/.atom/packages/flint/lib/errors.js:19

TypeError: Cannot read property 'split' of undefined
    at /Users/michael/.atom/packages/flint/lib/errors.js:19:33
    at Array.map (native)
    at refresh (/Users/michael/.atom/packages/flint/lib/errors.js:16:35)
    at EventEmitter.<anonymous> (/Users/michael/.atom/packages/flint/lib/errors.js:31:36)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at emit (/Users/michael/.atom/packages/flint/lib/flint.js:8:35)
    at Object.onMessage (/Users/michael/.atom/packages/flint/lib/flint.js:28:7)
    at WebSocket.connection.onmessage (/Users/michael/.atom/packages/flint/lib/socket.js:32:12)
```

Happy to provide any other details to help reproduce this.

**Comment by mglukhovsky** [comment]
Also, if there's a better place to open issues like this (e.g. the `flintjs/atom` repo), let me know.

**Comment by ncammarata** [comment]
Oh man, on every syntax error. Yeah, /atom is better. Is this in the atom beta or atom installed from atom's package manager

**Comment by mglukhovsky** [comment]
I believe I installed it with the `curl` script: `sh <(curl -L https://flint.love/beta)`.

Is there a better way to pick the right Atom script?

**Comment by natew** [comment]
Closing as we are moving to a whole new atom plugin
