### ISSUE TITLE
Error: Cannot find module 'ansi-regex'

### ISSUE THREAD

**Issue by ncammarata** [flintjs/flint#208]
After pulling and running make & bootstrap, I get this

````
Error: Cannot find module 'ansi-regex'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/flint-babel-core/node_modules/strip-ansi/index.js:2:17)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/flint-babel-core/node_modules/chalk/index.js:4:17)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/flint-babel-core/lib/helpers/code-frame.js:24:14)
````

until I manually install ```flint-babel-core``` in runner/node_modules

**Comment by natew** [comment]
can you clear out entirely all flint stuff in `npm root -g` and re-run?

**Comment by natew** [comment]
Closing I think new makefile fixes
